### ISSUE TITLE
Consider running tests under "Strict" mode instead of wrapping everything in IssuesNoWarning

### ISSUE THREAD

**Issue by acampbel** [nosnoc/nosnoc#137]
Very cool repo!

I see many of your tests are wrapping everything in IssuesNoWarning. However, you may be able to ensure all tests run without warning without needing to do this by using the "Strict" option for running tests, which adds a FailOnWarning plugin to the test runner. These effectively ensures that any warning that is issued causes a test failure (other than ones being directly tested using IssuesWarings/verifyWarning and warnings you have suppressed using SuppressedWarningsFixture)

Hope that helps!

**Comment by apozharski** [comment]
Thank you for the kind words!

We are currently working on expanding and porting the test suite to a recent redesign so this is extremely timely advice which I'll be applying.

@nurkanovic This will be included in the test updates in PR #75

**Comment by apozharski** [comment]
Once again thank you for the advice @acampbel . This is resolved in #134
